Fix/select all
carbon-tools/carbon pull request #99
Opened 2016-09-07 18:02 UTC by saadshahd

2016-09-07 18:03 UTC, saadshahd commented
Hey @mkhatib, Please check this PR as a fix for this issue #80

2016-09-25 23:34 UTC, mkhatib commented
Thanks for sending this out, there was a reason I switched form a single content editable on the whole editor and stuck with content editable from other components.

I can't remember what was it exactly, I'll try to run this locally and see if I can find any problems.

2016-10-04 06:35 UTC, mkhatib requested changes
@saadshahd tried to play with this locally and it breaks quiet few things. The reason I believe I did the `contenteditable` change was because cursors would be stuck in the wrong places between the `divs` `containers` and `layout`. 

If we can make sure that doesn't happen I am ok with changing the `contenteditable` situation. 

Let me know if you can do some more testing on this and see how to fix these issues.

2016-10-04 06:35 UTC, mkhatib commented on src/extensions/giphyComponent.js
> -      this.selectionDom.setAttribute('contenteditable', true);
This change is breaking the selection process of the elements (including `FigureComponent`). 

Try for example clicking on an image and notice that there's a cursor in the paragraph before hitting delete won't delete the image and instead would delete the character in previous paragraph.

2016-10-04 06:35 UTC, mkhatib commented on src/layout.js
> -  this.dom.setAttribute('contenteditable', false);
This is also a breaking change. This allows the cursor to be inside layout container. You can see this is breaking by staging an image and then sitting the cursor at a paragraph after that stage and click the back arrow to see the cursor moving into that layout and user would be able to type outside the editing area.

2016-12-30 21:12 UTC, closed without merging

2016-12-30 21:13 UTC, mkhatib commented
Thanks @saadshahd I've used the same methods you were using here in the other PR to fix this. Thanks for taking a stab at this 😄